---
services:
  csvserver:
    image: infracloudio/csvserver:latest
    container_name: csvserver
    volumes:
      - ./inputFile:/csvserver/inputdata:z
    networks:
      - csvserver
    environment:
      CSVSERVER_BORDER: Orange
    ports:
      - 9393:9300
    restart: on-failure
networks:
  csvserver:
