---

services:
  csvserver:
    image: infracloudio/csvserver:latest
    container_name: csvserver
    volumes:
      - ./inputFile:/csvserver/inputdata:z
    networks:
      - csvserver
    environment:
      CSVSERVER_BORDER: Orange
    ports:
      - 9393:9300
    restart: on-failure
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:9300 || exit 1"]
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 50s
  prometheus:
    image: prom/prometheus:v2.22.0
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:z
    networks:
      - csvserver
    ports:
      - 9090:9090
    restart: on-failure
    depends_on:
      csvserver:
        condition: service_healthy
networks:
  csvserver:
